version: '3'

x-spark-worker:
  environment:
    &spark-worker-env
    SPARK_MASTER : spark://spark-master:7077
    SPARK_WORKER_CORES : 2
    SPARK_WORKER_MEMORY : 1G
    SPARK_DRIVER_MEMORY : 1G
    SPARK_EXECUTOR_MEMORY : 1G
    SPARK_WORKLOAD : worker

  depends_on:
    &spark-worker-depends-on
    spark-master:
      condition: service_healthy

x-spark-common:
  &spark-common
  image: ${SPARK_IMAGE:-cluster-apache-spark:3.0.2}
  volumes:
    - ./bash:/opt/bash
    - ./data:/opt/spark-data
    - ./src:/opt/spark-apps
    - ./src/test:/opt/spark-apps/test

services:

  spark-master:
    <<: *spark-common
    ports:
      - "8000:8000"
      - "9090:8080"
      - "7077:7077"
      - "80:80"
    hostname : spark-master
    environment:
      - SPARK_WORKLOAD=master
    healthcheck:
      test: "curl --fail --silent  http://spark-master:8080 || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5


  spark-worker-a:
    <<: *spark-common
    hostname : spark-worker-a
    environment:
      <<: *spark-worker-env
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      <<: *spark-worker-depends-on

  spark-worker-b:
    <<: *spark-common
    hostname : spark-worker-b
    environment:
      <<: *spark-worker-env
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      <<: *spark-worker-depends-on

#  demo-database:
#    image: postgres:11.7-alpine
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=casa1234